# Generated by Django 4.2.4 on 2023-11-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uimage',
            field=models.ImageField(default=0, upload_to='user_image'),
            preserve_default=False,
        ),
    ]
