# Generated by Django 5.0.3 on 2024-03-06 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255, verbose_name='NAME')),
                ('pcat', models.CharField(max_length=255, verbose_name='Category')),
                ('subcat', models.CharField(max_length=255, verbose_name='Sub_Category')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('pdis', models.IntegerField(verbose_name='Discount')),
                ('fprice', models.IntegerField(verbose_name='Final_Price')),
                ('psize', models.CharField(max_length=255, verbose_name='Size')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('img1', models.ImageField(upload_to='Images', verbose_name='Image1')),
                ('img2', models.ImageField(upload_to='Images', verbose_name='Image2')),
                ('img3', models.ImageField(upload_to='Images', verbose_name='Image3')),
                ('img4', models.ImageField(upload_to='Images', verbose_name='Image4')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('u_id', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_id', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='productsApp.product')),
            ],
        ),
    ]
