# Generated by Django 5.0.3 on 2024-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_cat', models.CharField(max_length=255, verbose_name='Description')),
                ('ban_img', models.ImageField(upload_to='Images', verbose_name='Image1')),
            ],
        ),
    ]
