# Generated by Django 5.0.3 on 2024-03-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0003_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='exist',
            field=models.IntegerField(default=0),
        ),
    ]
