# Generated by Django 5.0.3 on 2024-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0005_remove_cart_exist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=200)),
                ('psub_name', models.CharField(max_length=200)),
                ('p_name', models.CharField(max_length=200)),
                ('p_price', models.CharField(max_length=200)),
                ('o_date', models.DateField()),
            ],
        ),
    ]
