# Generated by Django 5.0.3 on 2024-03-14 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0006_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='p_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='psub_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='p_id',
            field=models.ForeignKey(db_column='pid', default=1, on_delete=django.db.models.deletion.CASCADE, to='productsApp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='size',
            field=models.CharField(default=1, max_length=255, verbose_name='Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='u_id',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
