# Generated by Django 5.0.3 on 2024-03-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0008_alter_orders_o_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='p_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='u_id',
            field=models.CharField(max_length=100),
        ),
    ]
