# Generated by Django 5.0.3 on 2024-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0009_alter_orders_p_id_alter_orders_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='o_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
