# Generated by Django 5.0.3 on 2024-03-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0010_orders_o_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='u_id',
            new_name='u_username',
        ),
    ]
