# Generated by Django 5.0.3 on 2024-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0012_rename_p_id_orders_o_p_name_orders_o_sub_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fprice_tot',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
