# Generated by Django 4.2.4 on 2023-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_product_cat_alter_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdetails',
            field=models.CharField(default=0, max_length=500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='is available'),
        ),
    ]
