# Generated by Django 4.2.4 on 2023-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_product_pdetails_alter_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimages',
            field=models.ImageField(default=0, upload_to='appimages/products'),
            preserve_default=False,
        ),
    ]
