# Generated by Django 4.2.4 on 2023-10-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_product_pimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdiscount',
            field=models.IntegerField(default=0, verbose_name='Discount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pimages',
            field=models.ImageField(upload_to='appimages/products', verbose_name='Product images'),
        ),
    ]
